name: Python Application Workflow

on:
  push:
    branches:
    - master
    - develop
    - feature/setup_workflows
    - feature/setup_project
  pull_request:
jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    strategy:
      matrix:
        # python-version: [3.8, 3.9] 
        python-version: [3.9] 

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run package_tests
      # run: python -m unittest discover -s package_tests
      run: pytest package_tests
    - name: Run project
      run: python main.py
    
