name: Python Application Workflow

on:
  push:
    branches:
    - master
    - develop
    - feature/interface_step_2
  pull_request:
jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    strategy:
      matrix:
        # python-version: [3.8, 3.9] 
        python-version: [3.9] 

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install Xvfb
      run: sudo apt-get install xvfb

    - name: Run tests
      run: |
        # If you are using pytest for tests
        xvfb-run --auto-servernum --server-args="-screen 0 1024x768x24" pytest tests
        # Uncomment the following line if you have unittests to run
        # xvfb-run --auto-servernum --server-args="-screen 0 1024x768x24" python -m unittest discover -s tests

    - name: Run project with Xvfb
      run: xvfb-run --auto-servernum --server-args="-screen 0 1024x768x24" python main.py
